[DOWNSTREAM_PREFIX_AS215172]
enabled = true
ipv6 = true
from = "AS215172:AS-DOWNSTREAM"

[DOWNSTREAM_PREFIX_AS215172_IPV4]
enabled = true
ipv6 = false
from = "AS215172"

[DOWNSTREAM_PREFIX_AS211729]
enabled = true
ipv6 = true
from = "AS211729"

[DOWNSTREAM_PREFIX_AS12198]
enabled = true
ipv6 = true
from = "AS-JSMSR"

[DOWNSTREAM_PREFIX_AS210352]
enabled = true
ipv6 = true
from = "AS210352"

[DOWNSTREAM_PREFIX_AS204539_IPV4]
enabled = true
ipv6 = false
from = "AS-AXIC"

[DOWNSTREAM_PREFIX_AS204539_IPV46]
enabled = true
ipv6 = true
from = "AS-AXIC"

[DOWNSTREAM_PREFIX_AS140915]
enabled = true
ipv6 = true
from = "AS140915:AS-MKNT"

[DOWNSTREAM_PREFIX_AS216299]
enabled = true
ipv6 = true
from = "AS216299"

[DOWNSTREAM_PREFIX_AS154185]
enabled = true
ipv6 = true
from = "AS154185"
